eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
      hostname: localhost
      
 
      
microservice:
  authldap-service:
    endpoints:
      endpoint:
        uri: ldap://localhost:10390
        base: dc=example,dc=com
